services:
    agit.mlang.validator:
        class: Agit\MultilangBundle\EntityConstraint\MultilangValidator
        arguments: [ @agit.validation ]
        tags: [{ name: validator.constraint_validator, alias: multilang }]

    agit.validator.multilang:
        parent: agit.validator
        class: Agit\MultilangBundle\Plugin\MultilangStringValidator
        arguments: [ "@agit.intl.locale", "@agit.validator.string", "@agit.validator.regex" ]
        tags: [{ name: agit.validator, id: multilang }]

    agit.mlang.twig:
        class: Agit\MultilangBundle\Service\MultilangTwigExtension
        tags: [{ name: twig.extension }]
